### ISSUE TITLE
convenience function per controllare se il bot può postare in una chat

### ISSUE THREAD

**Issue by zeroone2numeral2** [zeroone2numeral2/bbr-staff-bot#62]
invia una typing action e restituisce false se non ci è permesso postare. dovrebbe funzionare in tutte le chat dove potremmo essere bloccati/rimossi. Dovrebbe dipendere da un'opzione in config

```py
if config.telegram.test_chats and not utilities.send_typing(context.bot, Union[Chat, User]):
  return
```

Che fare quando viene restituito false? eg. `Chat.left = True`, `User.blocked = True` - fattibile dalla funzione oppure prima del return

**Comment by RememberTheAir** [comment]
a che serviva?
