### ISSUE TITLE
resetta last_request quando un utente abbandona la chat utenti

### ISSUE THREAD

**Issue by RememberTheAir** [zeroone2numeral2/bbr-staff-bot#66]
https://t.me/c/1826583707/54

> Aggiungere la possibilità di riscrivere al bot nel caso si esce per sbaglio o per dei motivi da flytek.  
> Vale comunque come richiesta, bisognerà solo scrivere un paragrafo a riguardo nella sezione del bot dedicata ai Membri.  
> Per esempio "se dovessi uscire del gruppo riutilizza il bot e rifai la richiesta chiedendo di rientrare"

valutare la possibilità di aggiungere un'info agli admin se l'utente fa una nuova richiesta, per segnalare che era precedentemente parte della chat

**Comment by zeroone2numeral2** [comment]
chiudo senza resettare `last_request`: concordato con vlad che utenti che abbandonano volontariamente possono comunque mettersi in contatto con lo staff (vedi #71)
