### ISSUE TITLE
Messaggio fissato eventi

### ISSUE THREAD

**Issue by zeroone2numeral2** [zeroone2numeral2/bbr-staff-bot#98]
Possibilità (controllata da un `BotSetting`) di postare, il lunedì, l'elenco degli eventi della settimana
La lista deve venire aggiornata quando un nuovo evento viene pubblicato nel canale, magari con qualche minuto di ritardo (vedi come programmare i job in ptb), in modo che quando vengono pubblicati gli eventi alle 23:23 la lista venga aggiornata una sola volta e non una volta per ogni evento

La funzione che aggiorna la lista deve estrarla dal db quando viene eseguita

Altro:
- [ ] la lista precedente deve essere eliminata (?)
- [ ] al termine della lista potrebbe essere un'idea aggiungere gli eventi postati la scorsa settimana che sono considerati "non validi"
- [x] comando staff (gruppo/privato) per forzare aggiornamento lista
- [x] comando staff (gruppo/privato) per mandare nuovamente la lista nel canale
- [ ] comando per eliminare post tramite bot (`/delpmsg [link]`, imposta la proprietà `deleted` dell'istanza a true)
- [ ] gestire correttamente lista eventi vuota

Possibile implementazione: job eseguito ogni ora che estrae l'ultimo record di `PartiesMessage`, se il record risale a settimana scorsa ed oggi è lunedì e l'ora è >7, allora posta un nuovo messaggio e salva un nuovo `PartiesMessage`; altrimenti aggiorna quello precedente.

Ogni istanza di `PartiesMessage` conterrà la lista di `Event.id` (stringa json) postati l'ultima volta, in ordine crescente. Se la nuova lista differisce da questa lista, allora bisogna aggiornare il messaggio. In questo modo la lista verrà aggiornata solo se necessario.

Comunque potrebbe essere un'idea postare due messaggi nel canale: uno per le feste in italia, uno per le feste all'estero. In questo caso, quando si estrae l'ultimo `PartiesMessage`, è necessario estrarlo per il tipo di messaggio di riferimento. Alcuni tipi di messaggio potrebbero essere: "it_event", "notit_event", " invalid_parties_posted_last_week"

In sostanza tutta la procedura andrebbe eseguita su due filtri, tipo:
```py
filters = [Event.region.in_("it"), Event.region.not_in_("it"),]
for filter in filters:
  events = get_week_events(filter)
```

# IMPORTANTE: capire quando è necessario aggiornare la lista

Ogni volta che si riceve un aggiornamento dal canale eventi, e questo aggiornamento comporta la modifica di un `Event` che è necessario che venga riflessa nella lista nel canale, allora va popolato un flag apposito in `bot_data`. Sarà il flag che verrà controllato dal job per capire se è necessario aggiornare la lista degli eventi

**Comment by RememberTheAir** [comment]
Possibile implementazione: job eseguito ogni ora che estrae l'ultimo record di `PartiesMessage`, se il record risale a settimana scorsa ed oggi è lunedì e l'ora è >7, allora posta un nuovo messaggio e salva un nuovo `PartiesMessage`; altrimenti aggiorna quello precedente.

Ogni istanza di `PartiesMessage` conterrà la lista di `Event.id` (stringa json) postati l'ultima volta, in ordine crescente. Se la nuova lista differisce da questa lista, allora bisogna aggiornare il messaggio. In questo modo la lista verrà aggiornata solo se necessario.

Comunque potrebbe essere un'idea postare due messaggi nel canale: uno per le feste in italia, uno per le feste all'estero.

In sostanza tutta la procedura andrebbe eseguita su due filtri, tipo:
```py
filters = [Event.region.in_("it"), Event.region.not_in_("it"),]
for filter in filters:
  events = get_week_events(filter)
```

**Comment by zeroone2numeral2** [comment]
`PartiesMessage`:
- id
- chat_id
- message_id
- message_date
- message_edit_date (ultima volta che la lista è stata aggiornata)
- force_sent (se inviato forzatamente dallo staff)
- events_list (json-encoded lista di `Event.id`)
- deleted (se il messaggio è stato eliminato col comando apposito)
- ignore (se ignorare il messaggio quando si controlla se inviare una nuova lista)
- created_on
- updated_on

**Comment by zeroone2numeral2** [comment]
job rimossi: 4e35ac5
